In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle

In [3]:
base_plano_saude2 = pd.read_csv("plano_saude2.csv")
x_plano_saude2 = base_plano_saude2.iloc[:,0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:,1].values

In [4]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x_plano_saude2_scaled = scaler_x.fit_transform(x_plano_saude2)
scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1,1))

In [5]:
from sklearn.neural_network import MLPRegressor
regressor_rna_saude = MLPRegressor(max_iter=1000)
regressor_rna_saude.fit(x_plano_saude2_scaled,y_plano_saude2_scaled.ravel())

MLPRegressor(max_iter=1000)

In [6]:
regressor_rna_saude.score(x_plano_saude2_scaled,y_plano_saude2_scaled)

0.9587943921052781

In [7]:
grafico = px.scatter(x =x_plano_saude2_scaled.ravel(),y= y_plano_saude2_scaled.ravel())
grafico.add_scatter(x= x_plano_saude2_scaled.ravel(),y=regressor_rna_saude.predict(x_plano_saude2_scaled))
grafico.show()

In [8]:
novo = [[40]]
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [9]:
scaler_y.inverse_transform(regressor_rna_saude.predict(novo).reshape(-1,1))

array([[1146.85863834]])

In [10]:
bases_casas = pd.read_csv("house_prices.csv")

x_casas = bases_casas.iloc[:,3:19].values
y_casas = bases_casas.iloc[:,2].values

from sklearn.model_selection import train_test_split
x_casas_treinamento,x_casas_teste,y_casas_treinamento,y_casas_teste = train_test_split(x_casas,y_casas,test_size=0.3,random_state=0)

from sklearn.preprocessing import StandardScaler
scaler_x_casas = StandardScaler()
x_casas_treinamento_scaled = scaler_x_casas.fit_transform(x_casas_treinamento)
scaler_y_casas = StandardScaler()
y_casas_treinamento_scaled = scaler_y_casas.fit_transform(y_casas_treinamento.reshape(-1,1))

In [13]:
x_casas_teste_scaled = scaler_x_casas.transform(x_casas_teste)
y_casas_teste_scaled = scaler_y_casas.transform(y_casas_teste.reshape(-1,1))

In [12]:
regressor_rna_casas = MLPRegressor(max_iter=1000,hidden_layer_sizes=(9,9))
regressor_rna_casas.fit(x_casas_treinamento_scaled,y_casas_treinamento_scaled.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [14]:
regressor_rna_casas.score(x_casas_teste_scaled,y_casas_teste_scaled)

0.8841089883376688

In [18]:
previsoes = regressor_rna_casas.predict(x_casas_teste_scaled)
previsoes

array([-0.68784586,  2.59329188,  0.0340204 , ..., -0.53851562,
       -0.88430651, -0.89703284])

In [20]:
from sklearn.metrics import mean_absolute_error
scaler_y.inverse_transform(mean_absolute_error(y_casas_teste_scaled,previsoes).reshape(-1,1))

array([[3121.55190142]])