In [179]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.naive_bayes import GaussianNB

base_risco_credito = pd.read_csv("risco_credito.csv")
base_credit = pd.read_csv("credit_data.csv")
base_census = pd.read_csv("census.csv")



In [180]:
x_risco_credito = base_risco_credito.iloc[:,0:4].values
y_risco_credito = base_risco_credito.iloc[:,4].values

In [181]:
from sklearn.preprocessing import LabelEncoder
label_historia = LabelEncoder()
label_divida = LabelEncoder()
label_garantia = LabelEncoder()
label_renda = LabelEncoder()


In [182]:
x_risco_credito[:,0] = label_historia.fit_transform(x_risco_credito[:,0])
x_risco_credito[:,1] = label_divida.fit_transform(x_risco_credito[:,1])
x_risco_credito[:,2] = label_garantia.fit_transform(x_risco_credito[:,2])
x_risco_credito[:,3] = label_renda.fit_transform(x_risco_credito[:,3])

In [183]:
base_credit["age"][base_credit["age"]>0].mean()
base_credit.loc[base_credit["age"]<0,"age"] = 40.92

In [184]:
base_credit["age"].fillna(base_credit["age"].mean(),inplace=True)

C:\Users\teamd\AppData\Local\Temp\ipykernel_14528\2828547915.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  base_credit["age"].fillna(base_credit["age"].mean(),inplace=True)


In [185]:
x_credit = base_credit.iloc[:,1:4].values
y_credit = base_credit.iloc[:,4].values


In [186]:
from sklearn.preprocessing import StandardScaler
stand = StandardScaler()
x_credit = stand.fit_transform(x_credit)

In [187]:
x_census = base_census.iloc[:,0:14].values
y_cesus = base_census.iloc[:,14].values

In [188]:
#tranforma str em int
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
teste = label.fit_transform(x_census[:,1])
teste

array([7, 6, 4, ..., 4, 4, 5])

In [189]:
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()


In [190]:
x_census[:,1] = label_encoder_workclass.fit_transform(x_census[:,1])
x_census[:,3] = label_encoder_education.fit_transform(x_census[:,3])
x_census[:,5] = label_encoder_marital.fit_transform(x_census[:,5])
x_census[:,6] = label_encoder_occupation.fit_transform(x_census[:,6])
x_census[:,7] = label_encoder_relationship.fit_transform(x_census[:,7])
x_census[:,8] = label_encoder_race.fit_transform(x_census[:,8])
x_census[:,9] = label_encoder_sex.fit_transform(x_census[:,9])
x_census[:,13] = label_encoder_country.fit_transform(x_census[:,13])

In [191]:
x_census[0]

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 39], dtype=object)

In [192]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
onehotencoder_census = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,3,5,6,7,8,9,13])], remainder='passthrough')

In [193]:
x_census = onehotencoder_census.fit_transform(x_census).toarray()

In [194]:
x_census

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.1740e+03, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.5024e+04, 0.0000e+00,
        4.0000e+01]])

In [195]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
x_census = scaler_census.fit_transform(x_census)
x_census[0]

array([-0.2444502 , -0.17429511, -0.26209736, -0.01466381, -1.5167923 ,
       -0.18838933, -0.29093568,  4.90769968, -0.02073999, -0.17175325,
       -0.19348662, -0.11609195, -0.07201601, -0.10164955, -0.1422718 ,
       -0.12664495, -0.18406376, -0.21053433,  2.25399324, -0.11334387,
       -0.68994199, -0.23637391, -0.03960742, -0.13419553, -0.53714425,
       -0.39750806, -0.02658695, -0.92284068, -0.11403678,  1.43105786,
       -0.1802846 , -0.17735813, -0.24494366,  2.76348874, -0.01662771,
       -0.37949517, -0.37774555, -0.17745022, -0.20957797, -0.25595432,
       -0.33554133, -0.06780164, -0.38166338, -0.14260848, -0.35531609,
       -0.17127887, -0.22710355, -0.82533335,  1.70899099, -0.17624972,
       -0.42934582, -0.34403232, -0.22492681, -0.09820087, -0.18155194,
       -0.32576824, -0.09161163,  0.4130197 , -0.70307135,  0.70307135,
       -0.13502327, -0.02416321, -0.06107342, -0.0480488 , -0.04260602,
       -0.05409379, -0.04641598, -0.02933708, -0.05714946, -0.05

In [196]:
from sklearn.model_selection import train_test_split
x_census_treinamento,x_census_teste,y_census_treinamento,y_census_teste = train_test_split(x_census,y_cesus, test_size=0.15,random_state=0)

x_credit_treinamento,x_credit_teste,y_credit_treinamento,y_credit_teste = train_test_split(x_credit,y_credit,test_size=0.25,random_state=0)

In [197]:
import pickle
with open("census.pkl",mode="wb") as f:
    pickle.dump([x_census_treinamento,y_census_treinamento,x_census_teste,y_census_teste],f)

with open("credits.pkl",mode="wb") as f:
    pickle.dump([x_credit_treinamento,x_credit_teste,y_credit_treinamento,y_credit_teste],f)

with open("risco_credito.pkl","wb") as f:
    pickle.dump([x_risco_credito,y_risco_credito],f)

In [198]:
naive_risco_credito = GaussianNB()
naive_risco_credito.fit(x_risco_credito,y_risco_credito)

GaussianNB()

In [200]:
previsao = naive_risco_credito.predict([[0,0,1,2],[2,0,0,0]])

In [201]:
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [202]:
naive_risco_credito.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [203]:
naive_risco_credito.class_count_

array([6., 5., 3.])

In [204]:
naive_risco_credito.class_prior_

array([0.42857143, 0.35714286, 0.21428571])