In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle

In [2]:
with open("risco_credito.pkl","rb") as f:
    x_risco_credito,y_risco_credito = pickle.load(f)

In [3]:
x_risco_credito = np.delete(x_risco_credito, [2,7,11],axis = 0)
y_risco_credito = np.delete(y_risco_credito, [2,7,11],axis = 0)

In [6]:
from sklearn.linear_model import LogisticRegression
risco_credito_logistic = LogisticRegression(random_state = 1)
risco_credito_logistic.fit(x_risco_credito,y_risco_credito)

LogisticRegression(random_state=1)

In [7]:
risco_credito_logistic.intercept_

array([-0.80855152])

In [8]:
risco_credito_logistic.coef_

array([[-0.76706797,  0.23921064, -0.47989768,  1.12196145]])

In [9]:
previsoes1 = risco_credito_logistic.predict([[0,0,1,2],[2,0,0,0]])
previsoes1

array(['baixo', 'alto'], dtype=object)

In [10]:
with open("credits.pkl","rb") as f:
    x_credit_treinamento,x_credit_teste,y_credit_treinamento,y_credit_teste = pickle.load(f)

In [11]:
logistic_credits = LogisticRegression(random_state=1)
logistic_credits.fit(x_credit_treinamento,y_credit_treinamento)

LogisticRegression(random_state=1)

In [12]:
logistic_credits.intercept_

array([-6.03333114])

In [13]:
logistic_credits.coef_

array([[-2.55275554, -3.72391763,  3.94333319]])

In [14]:
previsoes2 = logistic_credits.predict(x_credit_teste)
previsoes2

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [15]:
logistic_credits.score(x_credit_teste,y_credit_teste)

0.946

In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_credit_teste,previsoes2))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       436
           1       0.79      0.78      0.79        64

    accuracy                           0.95       500
   macro avg       0.88      0.88      0.88       500
weighted avg       0.95      0.95      0.95       500



In [17]:
with open("census.pkl","rb") as f:
    x_census_treinamento,y_census_treinamento,x_census_teste,y_census_teste = pickle.load(f)

In [24]:
logistic_census = LogisticRegression(random_state=1)
logistic_census.fit(x_census_treinamento,y_census_treinamento)

LogisticRegression(max_iter=200, random_state=1)

In [25]:
logistic_census.intercept_

array([-2.10552416])

In [26]:
logistic_census.coef_

array([[-6.98488613e-02,  1.18355815e-01, -9.28364487e-03,
        -6.32571637e-02,  5.70026706e-02,  5.07381719e-02,
        -8.84284931e-02, -5.02268816e-02, -1.24694668e-01,
        -1.02481824e-01, -1.17822786e-01, -3.66227818e-02,
        -1.89874033e-02, -2.67960548e-02, -8.22889018e-02,
        -7.88822810e-02, -8.12332696e-03,  1.13390793e-02,
         1.45986267e-01,  1.18924828e-01, -7.54038219e-02,
         1.44347173e-01, -5.54400102e-01,  1.13453107e-01,
         2.46279059e-02, -1.90450912e-01,  4.34375255e-02,
         7.00139994e-01, -6.46427239e-02, -5.18599668e-01,
        -1.07259785e-01, -8.85445200e-02, -7.37373311e-02,
        -1.37206225e-02, -2.06416506e-02,  2.26862374e-02,
         2.52008753e-01, -1.67994077e-01, -1.41452274e-01,
        -8.40072161e-02, -2.57017139e-01, -2.82516289e-01,
         1.61879470e-01,  8.58540408e-02,  8.36697148e-02,
         1.09051852e-01, -2.53383593e-02, -2.30592713e-02,
         1.32752101e-01, -8.29001225e-02, -3.09430677e-0

In [27]:
previsoes3 = logistic_census.predict(x_census_teste)
previsoes3

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [28]:
logistic_census.score(x_census_teste,y_census_teste)

0.8497441146366428

In [21]:
print(classification_report(y_census_teste,previsoes3))

              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      3693
        >50K       0.73      0.61      0.66      1192

    accuracy                           0.85      4885
   macro avg       0.81      0.77      0.78      4885
weighted avg       0.84      0.85      0.84      4885

