In [52]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle

In [53]:
base_plano_saude2 = pd.read_csv("plano_saude2.csv")
base_plano_saude2

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [54]:
x_plano_saude2 = base_plano_saude2.iloc[:,0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:,1].values

In [55]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 4)
x_plano_saude2_Poly = poly.fit_transform(x_plano_saude2)

In [56]:
from sklearn.linear_model import LinearRegression
regressor_saude_polinomial = LinearRegression()
regressor_saude_polinomial.fit(x_plano_saude2_Poly,y_plano_saude2)

LinearRegression()

In [57]:
regressor_saude_polinomial.intercept_

16561.974637941225

In [58]:
regressor_saude_polinomial.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [59]:
novo = [[40]]
novo = poly.transform(novo)
novo

array([[1.00e+00, 4.00e+01, 1.60e+03, 6.40e+04, 2.56e+06]])

In [60]:
regressor_saude_polinomial.predict(novo)

array([1335.33958016])

In [61]:
previsoes = regressor_saude_polinomial.predict(x_plano_saude2_Poly)
previsoes

array([ 549.65035466,  345.85081577,  616.53845994,  975.83915951,
       1249.06759854, 1472.72727271, 1894.51048941, 2973.29836768,
       5379.16083826, 9993.35664352])

In [62]:
grafico = px.scatter(x =x_plano_saude2[:,0],y= y_plano_saude2)
grafico.add_scatter(x= x_plano_saude2[:,0],y=previsoes)
grafico.show()

In [63]:
regressor_saude_polinomial.score(x_plano_saude2_Poly,y_plano_saude2)

0.9976494147321988

In [64]:
bases_casas = pd.read_csv("house_prices.csv")

x_casas = bases_casas.iloc[:,3:19].values
y_casas = bases_casas.iloc[:,2].values

In [65]:
from sklearn.model_selection import train_test_split
x_casas_treinamento,x_casas_teste,y_casas_treinamento,y_casas_teste = train_test_split(x_casas,y_casas,test_size=0.3,random_state=0)

In [66]:
poly_casa = PolynomialFeatures(degree= 2)
x_casas_treinamento_poly = poly_casa.fit_transform(x_casas_treinamento)
x_casas_teste_poly = poly_casa.transform(x_casas_teste)

In [67]:
regressor_casa_polinomial = LinearRegression()
regressor_casa_polinomial.fit(x_casas_treinamento_poly,y_casas_treinamento)

LinearRegression()

In [68]:
regressor_casa_polinomial.intercept_

35640872284.736885

In [69]:
regressor_casa_polinomial.coef_

array([-1.65542870e+03,  9.98163074e+06, -1.55663267e+07,  1.37019685e+06,
       -3.45951960e+01, -1.64917231e+07,  9.70743336e+07,  4.17176687e+06,
        4.85115262e+06, -2.62594078e+07, -1.32835251e+06, -1.36774112e+06,
       -4.00002445e+05,  4.20141589e+04, -8.36003639e+05,  3.89330562e+07,
       -8.01609196e+07,  8.02674850e+02, -7.97860599e+03, -1.19903115e+04,
        1.21868858e-02,  1.68727297e+04,  1.59844044e+04,  2.85570893e+03,
       -7.38459919e+03, -7.91555783e+02,  1.19800204e+04,  1.19898566e+04,
       -7.76607523e+01, -9.76844535e+00, -1.75581794e+01, -2.92486673e+04,
        5.47073517e+04, -3.69314495e+03, -1.70483910e+02, -2.74651470e-01,
       -3.47374336e+04, -1.67237230e+04,  3.84723525e+03, -6.25133888e+03,
        1.36884562e+04,  2.04044193e+02,  1.73061569e+02,  2.91002051e+02,
       -1.45587529e+01,  3.34308220e+01,  4.70052067e+04, -7.73422845e+04,
       -4.70381604e+05,  6.43797080e+04, -2.74905362e+02,  1.01901979e+02,
        4.27995150e+00,  

In [70]:
previsoes = regressor_casa_polinomial.predict(x_casas_teste_poly)
previsoes

array([ 386700.96342468, 1988530.06944275,  577538.51132965, ...,
        432204.62067413,  237164.13674927,  123855.86647034])

In [71]:
regressor_casa_polinomial.score(x_casas_teste_poly,y_casas_teste)

0.8152949072365525